### ISSUE TITLE
[Q&A] Lanucher.exe - Lanuched.ico `Cannot open file`

### ISSUE THREAD

**Issue by bachig26** [r57zone/DSAdvance#1]
![lanucher exe](https://user-images.githubusercontent.com/96393348/166856149-6e7339b3-a51f-498a-8ded-01d279dc10b7.jpg)

I was trying to open the lanucher.exe after reading the ReadMe about the autorun.

I'm getting this error message. Will this be solved if I set the `Lanucher.exe` in Startup and restart the PC or is this error related to some other like the missing file?

**Comment by r57zone** [comment]
Hi, fixed it, thanks. Download again.
