### ISSUE TITLE
(Emulation: Xbox gamepad) vibration doesn't work (wireless mode)

### ISSUE THREAD

**Issue by uomar8** [r57zone/DSAdvance#15]
i tested Xbox vibration using this website
https://hardwaretester.com/gamepad

Sony PS4 Dualshock Test Vibration is good
but (Emulation: Xbox gamepad) Test Vibration doesn't work

![image](https://github.com/r57zone/DSAdvance/assets/7046347/b52d6bdf-5708-4637-bceb-698bd4afee93)

**Comment by r57zone** [comment]
In wireless mode or wired mode?

**Comment by uomar8** [comment]
> wireless mode

 wireless mode only, wired mode works fine 

 "test program XInputTest.exe" i don't think it support this type of test

**Comment by r57zone** [comment]
There is a vibration in the XInputTest.exe program, one slider does not work, but the second one works. I think it's worth checking the vibration there or in some game.

**Comment by uomar8** [comment]
> There is a vibration in the XInputTest.exe program, one slider does not work, but the second one works. I think it's worth checking the vibration there or in some game.

i just checked XInputTest.exe program both work for me right and left motors (wired mode)

(wireless mode) both not working

**Comment by r57zone** [comment]
Fixed in the new version, also fixed backlight and battery indication
https://github.com/r57zone/DSAdvance/releases/
