### ISSUE TITLE
Zip file getting labeled as virus by multiple sources

### ISSUE THREAD

**Issue by Xelo2000** [r57zone/DSAdvance#2]
VirusTotal results:

https://www.virustotal.com/gui/file/c31ffcdea1d1b12310c268cc7d015348380c556c5dbe127b48739b1cc8a736b4/detection

**Comment by r57zone** [comment]
I don't care what garbage antiviruses show. If you want, you can write to your antivirus company, send the source and archive, they will probably fix it, but I'm not interested in doing this. If you want, download Microsoft Visual Studio 2017 and build the sources yourself and you will get the same size and the same results of garbage antiviruses.

**Comment by r57zone** [comment]
I wrote to several antivirus companies, here AVG answered and removed false positive
![](https://user-images.githubusercontent.com/9499881/172184074-b6bf49d5-2d7d-40ae-a31e-240100413d8b.png)
If others answer I will write

**Comment by r57zone** [comment]
Antiviruses mark any new application as a virus if they see network functions, dynamic dll loading, etc.

**Comment by r57zone** [comment]
![Screenshot 1](https://user-images.githubusercontent.com/9499881/172356243-de0ab3bc-6ac0-42fd-b902-97874d0857a9.png)
